name: Test Whitespace and line endings

on: [pull_request]

jobs:
  eclint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '12.x'
      - run: npm i -g eclint
      - run: eclint check
